fix: added new exception for uniqueness of client name
supertokens/supertokens-plugin-interface pull request #102
Opened 2023-06-07 05:57 UTC by AdithyaSSup

## Summary of change
Exception to identify unique name violation

## Related issues
- https://github.com/supertokens/supertokens-core/issues/582

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2023-06-27 06:38 UTC, rishabhpoddar requested changes

2023-06-27 06:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Storage.java
>              throws StorageQueryException, UnknownOAuth2ClientIdException;
rename `removeOAuth2Client` to `removeOAuth2ClientById`

2023-06-27 06:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Storage.java
> +    void updateOAuth2TokenInfoByRefreshTokenHash(TenantIdentifier tenantIdentifier, OAuth2TokenInfo tokenInfo)
Don't need this function cause we already have `updateOAuth2TokenInfoByRefreshTokenHash_Transaction`

2023-06-27 06:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/exception/UnknownRedirectURIException.java
> +import java.security.spec.ECFieldF2m;
what is this import?

2023-06-27 06:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Storage.java
>      void removeOAuth2ClientScope(AppIdentifier appIdentifier, String clientId, String scope)
don't need this cause we already have `removeOAuth2ClientScope_Transaction`

2023-06-27 06:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Storage.java
>      List<OAuth2ClientScope> getOAuth2ClientScopes(AppIdentifier appIdentifier, String clientId)
don't need this cause we already have `getOAuth2ClientScopes_Transaction`

2023-06-27 06:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/sqlStorage/OAuth2SQLStorage.java
> +            throws StorageQueryException, UnknownOAuth2ClientSecretHashException;
do you need this function? Cause we already have `getOAuth2ClientById` which should also return the secret hash and then you can compare the secret hash from the db with the input.

Also, if we are removing this, then we should add `getOAuth2ClientById_Transaction` and then remove the `getOAuth2ClientById` from the StorageLayer file.

2023-06-27 06:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/sqlStorage/OAuth2SQLStorage.java
> +                                                                     String clientId, String refreshTokenHash)
don't need this cause you already have `getOAuth2ClientById`, and then you can compare the refresh token input with the hashed value from the db in the core logic. 

If we are doing this, then you will need to remove this function and add `getOAuth2ClientById_Transaction`. You also won't need.

2023-06-27 06:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/sqlStorage/OAuth2SQLStorage.java
> +    OAuth2TokenInfo getOAuth2TokenInfoByAccessTokenHash_Transaction(TenantIdentifier tenantIdentifier, TransactionConnection con, String accessTokenHash)
I'm not sure that we should have this as a transaction - i think in dbs, when you do a select for update, the lock is taken based on the where clause condition. If there are other places where the tokens table rows are locked based on the `id`, but here you are locking based on `accessTokenHash`, it may cause issues.

Please investigate if locking happens properly or not in this case (for psql and mysql). If it doesn't we may need to streamline the functions to have locking based on one column type per table. So for example, in the deleted tokens API with accessTokenHash, instead of locking based on accessTokenHash, we should first fetch the row associated with accessTokenHash (without locking), and then acquire a lock based on the `id` of that row, and then proceed with the logic after that.

That being said, why are we taking a lock in the delete token API with accessTokenHash in the first place?

2023-06-28 07:23 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/sqlStorage/OAuth2SQLStorage.java
> +                                                                     String clientId, String refreshTokenHash)
>don't need this cause you already have getOAuth2ClientById, and then you can compare the refresh token input with the hashed value from the db in the core logic.

I didnt understand this part..  AFAIK.. this function gets the token info in order to check the `refreshtokenhash` and `scope` values from db against the inputs.. 

Also `getOAuth2ClientById ` does not return refreshtoken details.

2023-06-28 07:34 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Storage.java
>              throws StorageQueryException, UnknownOAuth2ClientIdException;
changes made.

2023-06-28 07:34 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Storage.java
> +    void updateOAuth2TokenInfoByRefreshTokenHash(TenantIdentifier tenantIdentifier, OAuth2TokenInfo tokenInfo)
changes made

2023-06-28 07:35 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/exception/UnknownRedirectURIException.java
> +import java.security.spec.ECFieldF2m;
not required. removed.

2023-06-28 07:35 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Storage.java
>      void removeOAuth2ClientScope(AppIdentifier appIdentifier, String clientId, String scope)
changes made

2023-06-28 07:35 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Storage.java
>      List<OAuth2ClientScope> getOAuth2ClientScopes(AppIdentifier appIdentifier, String clientId)
changes made

2023-06-28 08:03 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/sqlStorage/OAuth2SQLStorage.java
> +            throws StorageQueryException, UnknownOAuth2ClientSecretHashException;
`getOAuth2ClientByIdAndClientSecretHash_Transaction ` we don't need this method.

Also `getOAuth2ClientById_Transaction ` is not required as there are no cascading operations that needs locking or rollback of `client` table fields.

2023-06-28 14:35 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/sqlStorage/OAuth2SQLStorage.java
> +    OAuth2TokenInfo getOAuth2TokenInfoByAccessTokenHash_Transaction(TenantIdentifier tenantIdentifier, TransactionConnection con, String accessTokenHash)
Yes , this method  and `removeOAuth2TokenInfoByAccessTokenHash` need not be a part of transaction.
changes made.

2024-07-09 10:56 UTC, closed without merging