Mfa multitenancy
supertokens/supertokens-plugin-interface pull request #122
Opened 2023-10-13 07:04 UTC by sattvikc

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-10-19 05:59 UTC, rishabhpoddar requested changes

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +                    throw new IllegalArgumentException("Factor " + factor + " is not a built-in factor");
throw a compile time error instead

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +                        throw new IllegalArgumentException("Factor " + factorStr + " cannot be used as a custom factor");
throw a compile time error

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +                    throw new IllegalArgumentException("Invalid custom factor in the input");
throw a compile time error

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +    public final String[] defaultRequiredFactors;
needs to be MFARequirement[] (see node sdk types)

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +public class MfaFirstFactors {
Change this to not be a list

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +public class MfaFirstFactors {
```suggestion
public class MfaFirstFactor {
```

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +    public MfaConfig(MfaFirstFactors firstFactors, String[] defaultRequiredFactors) {
```suggestion
    public MfaConfig(MfaFirstFactor[] firstFactors, MFARequirement[] defaultRequiredFactors) {
```

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
> +                        @Nonnull MfaConfig mfaConfig,
this is nullable

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
> +        tenantConfigObject.get("mfa").getAsJsonObject().add("firstFactors", this.mfaConfig.firstFactors.toJson());
this may not be there., in which case, we do not add firstFactor

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
also add the defaultRequiredFactors

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +    public final String[] defaultRequiredFactors;
mark these as nullable

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +        this.defaultRequiredFactors = defaultRequiredFactors == null ? new String[0] : defaultRequiredFactors;
don't default to empty array. Keep it null cause it's important to distinguish these cases.

2023-10-19 05:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +            return this.firstFactors.equals(otherMfaConfig.firstFactors) && thisdefaultRequiredFactors.equals(otherdefaultRequiredFactors);
they are nullable

2023-10-20 07:45 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +                    throw new IllegalArgumentException("Factor " + factor + " is not a built-in factor");
No more required

2023-10-20 07:46 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +                        throw new IllegalArgumentException("Factor " + factorStr + " cannot be used as a custom factor");
No more required

2023-10-20 07:46 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +    public final String[] defaultRequiredFactors;
converted to String[]

2023-10-20 07:46 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +public class MfaFirstFactors {
changed to String[]

2023-10-20 07:47 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +public class MfaFirstFactors {
this class is removed

2023-10-20 07:47 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +    public MfaConfig(MfaFirstFactors firstFactors, String[] defaultRequiredFactors) {
both changed to String[]

2023-10-20 07:48 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
> +                        @Nonnull MfaConfig mfaConfig,
MfaConfig is nonnull but firstfactors and defaultRequiredFactorIds are nullable

2023-10-20 07:48 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +    public final String[] defaultRequiredFactors;
done

2023-10-23 08:38 UTC, rishabhpoddar requested changes

2023-10-23 08:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +        return new GsonBuilder().serializeNulls().create().toJsonTree(this).getAsJsonObject();
if firstFactors or  defaultRequiredFactorIds is null, what will this do? Not have them in the result or have them, but as null?

2023-10-23 08:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +    private boolean compareStrArray(String[] arr1, String[] arr2) {
move this function to a utils file?

2023-10-23 08:38 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
> +        tenantConfigObject.add("mfa", this.mfaConfig.toJson());
The input JSON does not contain the MFA prop, so the output should also not contain it.

2023-10-25 05:16 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +    private boolean compareStrArray(String[] arr1, String[] arr2) {
Done

2023-10-25 12:13 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaFirstFactors.java
> +                    throw new IllegalArgumentException("Invalid custom factor in the input");
Not required

2023-10-25 12:14 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/TenantConfig.java
> +        tenantConfigObject.get("mfa").getAsJsonObject().add("firstFactors", this.mfaConfig.firstFactors.toJson());
Done

2023-10-25 12:14 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +        this.defaultRequiredFactors = defaultRequiredFactors == null ? new String[0] : defaultRequiredFactors;
Done

2023-10-25 12:14 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +            return this.firstFactors.equals(otherMfaConfig.firstFactors) && thisdefaultRequiredFactors.equals(otherdefaultRequiredFactors);
Removed this class

2023-10-25 12:15 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MfaConfig.java
> +        return new GsonBuilder().serializeNulls().create().toJsonTree(this).getAsJsonObject();
Removed class

2023-10-26 06:01 UTC, merged