feat: Add a new method to fetch the config as json
supertokens/supertokens-plugin-interface pull request #137
Opened 2024-02-08 06:35 UTC by prateek3255

## Summary of change

Adds a new method to the interface to fetch the config of the plugin as json

## Related issues
N/A

## Checklist for important updates
- [x] Changelog has been updated
- [x] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
N/A

2024-02-19 09:38 UTC, sattvikc requested changes

2024-02-19 09:38 UTC, sattvikc commented on build.gradle
> +version = "4.0.6"
Version update is not required now, this will be on top of MFA

2024-02-19 09:38 UTC, sattvikc commented on CHANGELOG.md
> +- Add a new method `getConfigFieldsJson` to fetch the plugin config as json
keep this under Unreleased

2024-02-19 09:38 UTC, sattvikc commented on CHANGELOG.md
>  ## [4.0.5] - 2023-12-05
Create a base branch `feat/mfa-dashboard` off latest version and then update this PR to merge into that instead of 4.0

2024-02-19 09:38 UTC, sattvikc commented on CHANGELOG.md
>  ## [4.0.5] - 2023-12-05
Same applies for the core and the plugins

2024-02-21 12:15 UTC, prateek3255 commented on CHANGELOG.md
> +- Add a new method `getConfigFieldsJson` to fetch the plugin config as json
Done

2024-02-21 12:15 UTC, prateek3255 commented on CHANGELOG.md
>  ## [4.0.5] - 2023-12-05
Done

2024-02-22 05:13 UTC, sattvikc requested changes

2024-02-22 05:13 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/Storage.java
> +    JsonArray getConfigFieldsJson();
```suggestion
    JsonArray getConfigFieldsInfo();
```

2024-02-22 05:13 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/Storage.java
> +
Might be better to return an array of known type. JsonArray is very generic, and difficult to know what all information this will return.

2024-02-23 05:21 UTC, prateek3255 commented on src/main/java/io/supertokens/pluginInterface/Storage.java
> +    JsonArray getConfigFieldsJson();
Done

2024-02-23 05:21 UTC, prateek3255 commented on src/main/java/io/supertokens/pluginInterface/Storage.java
> +
Done

2024-02-23 08:38 UTC, sattvikc requested changes

2024-02-23 08:38 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/ConfigFieldInfo.java
> +    public String[] options;
Don't they need to have some JSON annotation?

2024-02-23 12:14 UTC, sattvikc requested changes

2024-02-23 12:14 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/ConfigFieldInfo.java
> +    public String[] options;
This needs a `@Nullable`

2024-02-23 12:14 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/ConfigFieldInfo.java
> +    public ConfigFieldInfo(String name, String description, boolean isDifferentAcrossTenants, String type) {
Nonnull and Nullable goes in for the parameters as well

2024-02-23 12:29 UTC, prateek3255 commented on src/main/java/io/supertokens/pluginInterface/ConfigFieldInfo.java
> +    public String[] options;
Fixed

2024-02-23 12:29 UTC, prateek3255 commented on src/main/java/io/supertokens/pluginInterface/ConfigFieldInfo.java
> +    public ConfigFieldInfo(String name, String description, boolean isDifferentAcrossTenants, String type) {
Fixed

2024-02-28 08:19 UTC, sattvikc approved these changes

2024-02-28 08:19 UTC, merged