feat: Add delete bulk import users api
supertokens/supertokens-plugin-interface pull request #139
Opened 2024-02-23 07:01 UTC by anku255

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2024-02-23 08:33 UTC, rishabhpoddar requested changes

2024-02-23 08:33 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
> +
this PR should only be about delete user.

2024-02-23 08:42 UTC, rishabhpoddar requested changes

2024-02-23 08:42 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
> +    void updateBulkImportUserStatus(AppIdentifier appIdentifier, @Nonnull String bulkImportUserId, @Nonnull BulkImportUserStatus status) throws StorageQueryException;
this goes in a transaction

2024-02-27 10:43 UTC, anku255 commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
> +    void updateBulkImportUserStatus(AppIdentifier appIdentifier, @Nonnull String bulkImportUserId, @Nonnull BulkImportUserStatus status) throws StorageQueryException;
done

2024-03-20 07:36 UTC, closed without merging