feat: Add a new method to fetch the config as json
supertokens/supertokens-plugin-interface pull request #146
Opened 2024-03-18 07:39 UTC by prateek3255

## Summary of change

Adds a new method to the interface to fetch the config of the plugin

## Related issues

N/A

## Checklist for important updates
- [x] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Update the interface to include value of properties as well

2024-05-05 06:29 UTC, rishabhpoddar requested changes

2024-05-05 06:29 UTC, rishabhpoddar commented on CHANGELOG.md
> +- Add a new method `getConfigFieldsJson` to fetch the plugin config as json
add a version

2024-05-05 06:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/annotations/ConfigDescription.java
> +@Target(ElementType.FIELD)
what does this mean? Please add comments

2024-05-05 06:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/annotations/ConfigDescription.java
> +
why is this class needed?

2024-05-05 06:29 UTC, rishabhpoddar commented on CHANGELOG.md
> +- Add a new method `getConfigFieldsJson` to fetch the plugin config as json
+ other changes

2024-05-07 06:20 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/annotations/ConfigDescription.java
> +
Used as an annotation on the fields of CoreConfig and PostgreSQLConfig so that the descriptions can be read at runtime from the API

2024-05-07 06:21 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/annotations/ConfigDescription.java
> +@Target(ElementType.FIELD)
Done

2024-05-07 08:57 UTC, sattvikc commented on CHANGELOG.md
> +- Add a new method `getConfigFieldsJson` to fetch the plugin config as json
Release prep at the end

2024-05-24 10:34 UTC, merged