feat: Add BulkImport APIs and cron
supertokens/supertokens-plugin-interface pull request #148
Opened 2024-03-20 07:31 UTC by anku255

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2024-03-20 12:21 UTC, rishabhpoddar requested changes

2024-03-20 12:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/bulkimport/sqlStorage/BulkImportSQLStorage.java
> +            TransactionConnection con, @Nonnull String[] bulkImportUserIds, @Nonnull BULK_IMPORT_USER_STATUS status, @Nullable String errorMessage) throws StorageQueryException;
this should take just one bulkImportUserId and not an array

2024-03-20 12:21 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
> +    List<BulkImportUser> getBulkImportUsersForProcessing(AppIdentifier appIdentifier, @Nonnull Integer limit) throws StorageQueryException;
```suggestion
    List<BulkImportUser> getBulkImportUsersAndChangeStatusToProcessing(AppIdentifier appIdentifier, @Nonnull Integer limit) throws StorageQueryException;
```

2024-03-21 10:47 UTC, anku255 commented on src/main/java/io/supertokens/pluginInterface/bulkimport/sqlStorage/BulkImportSQLStorage.java
> +            TransactionConnection con, @Nonnull String[] bulkImportUserIds, @Nonnull BULK_IMPORT_USER_STATUS status, @Nullable String errorMessage) throws StorageQueryException;
done

2024-03-21 10:47 UTC, anku255 commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
> +    List<BulkImportUser> getBulkImportUsersForProcessing(AppIdentifier appIdentifier, @Nonnull Integer limit) throws StorageQueryException;
done

2024-03-29 13:22 UTC, anku255 commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
> +    void updateBulkImportUserPrimaryUserId(AppIdentifier appIdentifier, @Nonnull String bulkImportUserId, @Nonnull String primaryUserId) throws StorageQueryException;
Ah.. yeah.. it does.. Don't know how I missed that 😅 . Will make this change.

2024-03-29 13:26 UTC, anku255 commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportStorage.java
> +    void updateBulkImportUserPrimaryUserId(AppIdentifier appIdentifier, @Nonnull String bulkImportUserId, @Nonnull String primaryUserId) throws StorageQueryException;
No, there is no point in making this a transaction. It will use a different connection than the bulkImport storage anyways and we will have to commit it.

We have already handled the case where this query would succeed but further queries will not.

2024-04-17 06:09 UTC, sattvikc requested changes

2024-04-17 06:09 UTC, sattvikc commented on build.gradle
> +version = "6.0.1"
```suggestion
version = "6.1.0"
```

2024-04-18 10:26 UTC, anku255 commented on build.gradle
> +version = "6.0.1"
Fixed. Thanks for catching it.

2024-04-22 06:23 UTC, sattvikc requested changes

2024-04-22 06:23 UTC, sattvikc commented on build.gradle
> +version = "6.1.0"
update branch with latest and update versions accordingly

2024-04-29 10:58 UTC, anku255 commented on build.gradle
> +version = "6.1.0"
done

2024-05-05 07:13 UTC, rishabhpoddar requested changes

2024-05-05 07:13 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportUser.java
> +    }
these two fucntions are very unclear. As a reader of this code, it makes no sense why they are there. Please add more detailed comment with examples.

2024-05-29 07:19 UTC, anku255 commented on src/main/java/io/supertokens/pluginInterface/bulkimport/BulkImportUser.java
> +    }
I have added comment to explain the purpose of these functions. That should help explain it.

2024-11-27 11:14 UTC, closed without merging