Add the ability to create JWTs using supertokens
supertokens/supertokens-plugin-interface pull request #22
Opened 2021-08-26 15:37 UTC by nkshah2

## Summary of change
- Adds a new recipe id for the JWT recipe
- Changes to storage interfaces for the JWT recipe

## Related issues
- https://github.com/supertokens/for-zenhub/issues/16

## Related Pull Requests
- https://github.com/supertokens/supertokens-core/pull/302

## Checklist for important updates
- [ ] Changelog has been updated
- [x] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [x] Update build.gradle version
- [ ] Update CHANGELOG

2021-08-30 05:12 UTC, nkshah2 commented on src/main/java/io/supertokens/pluginInterface/jwt/JWTAsymmetricSigningKeyInfo.java
> +    public String getKeyString() {
This was missed in cleanup, the method has been removed and the keyString property is now public

2021-08-30 05:13 UTC, nkshah2 commented on src/main/java/io/supertokens/pluginInterface/jwt/JWTSigningKeyInfo.java
> +        this.keyString = keyString;
The keyString is used when setting in DB

2021-08-30 05:13 UTC, nkshah2 commented on src/main/java/io/supertokens/pluginInterface/jwt/JWTSigningKeyInfo.java
> +    public JWTAsymmetricSigningKeyInfo getAsAsymmetric() {
Done

2021-08-30 05:18 UTC, nkshah2 commented on src/main/java/io/supertokens/pluginInterface/jwt/exceptions/JWTException.java
> +/*
I liked the idea of having a wrapper exception class for individual recipes so that you could do something like this

```java
try {
    // do something
} catch (JWTException e) {
    // Handle all errors from the JWT recipe collectively if you want to
}
```

But in hindsight that feels like overkill and bad practice (plus a user would cascade catch to achieve the same thing anyway). Removed the JWTException class

2021-08-30 05:19 UTC, nkshah2 commented on src/main/java/io/supertokens/pluginInterface/jwt/exceptions/DuplicateKeyIdException.java
> +public class DuplicateKeyIdException extends JWTException {
Done

2021-08-30 05:32 UTC, rishabhpoddar approved these changes

2021-08-30 05:32 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/jwt/JWTSigningKeyInfo.java
>  public class JWTSigningKeyInfo {
@nkshah2 you missed this.

2021-08-30 05:34 UTC, nkshah2 commented on src/main/java/io/supertokens/pluginInterface/jwt/JWTSigningKeyInfo.java
>  public class JWTSigningKeyInfo {
Done

2021-08-30 05:34 UTC, rishabhpoddar approved these changes

2021-09-08 08:41 UTC, rishabhpoddar requested changes

2021-09-08 08:41 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/jwt/JWTAsymmetricSigningKeyInfo.java
> +        super(keyId, createdAtTime, algorithm, "");
- Shouldn't this be `super(keyId, createdAtTime, algorithm, keyString);`?

2021-09-08 10:33 UTC, rishabhpoddar approved these changes

2021-09-08 10:34 UTC, merged