Multiple access token signin keys
supertokens/supertokens-plugin-interface pull request #24
Opened 2021-09-09 11:26 UTC by porcellus

## Summary of change
This will allow us to store multiple access token signing keys. It still provides access to the signing keys stored in key-value storage through the methods with "Legacy" in their name.

SQL db changes:
```sql
CREATE TABLE `access_token_signing_keys` (
  `created_at_time` bigint unsigned NOT NULL,
  `value` text,
  PRIMARY KEY (`created_at_time`)
)
```
NoSQL:
It's not implemented yet, but I propose storing these in a single array value instead of a new collection. This way it's easy to keep the atomicity of the update operation.

## Related issues
- supertokens/supertokens-core#305

## Checklist for important updates
- [x] Changelog has been updated
- [x] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2021-09-09 11:52 UTC, rishabhpoddar requested changes

2021-09-09 11:52 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/session/noSqlStorage/SessionNoSQLStorage_1.java
> +    boolean removeAccessTokenSigningKeysBefore_Transaction(long createdAt)
It's not actually `createdAt` but should be `time`

2021-09-09 11:52 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/session/sqlStorage/SessionSQLStorage.java
> +    void removeAccessTokenSigningKeysBefore_Transaction(TransactionConnection con, long createdAtTime)
Change `createdAtTime` to `time`

2021-09-13 09:00 UTC, rishabhpoddar approved these changes

2021-09-15 07:22 UTC, rishabhpoddar requested changes

2021-09-15 07:22 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/session/noSqlStorage/SessionNoSQLStorage_1.java
> +    boolean addAccessTokenSigningKey_Transaction(KeyValueInfo info, long lastCreated)
- What's the purpose of `lastCreated` again? Perhaps it should be called `lastUpdated`?
- And I thought that we are not using last updated here since we will check the timeCreated of the first item in the array.

2021-09-15 07:29 UTC, porcellus commented on src/main/java/io/supertokens/pluginInterface/session/noSqlStorage/SessionNoSQLStorage_1.java
> +    boolean addAccessTokenSigningKey_Transaction(KeyValueInfo info, long lastCreated)
- `lastCreated` is used to check if the array changed between reading and this writing attempt. 
- I called it `lastCreated`, because it's the `created_at_time` of the first item in the array known by the "transaction"

2021-09-15 07:37 UTC, rishabhpoddar approved these changes

2021-09-15 08:21 UTC, rishabhpoddar approved these changes

2021-09-16 16:03 UTC, rishabhpoddar approved these changes

2021-09-22 11:13 UTC, merged