Passwordless
supertokens/supertokens-plugin-interface pull request #27
Opened 2021-11-16 15:34 UTC by porcellus

## Summary of change
Adding interfaces necessary to implement the passwordless recipe

## Related issues
- supertokens/supertokens-core#321
- supertokens/supertokens-core#322

## Checklist for important updates
- [x] Changelog has been updated
- [x] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2021-11-17 06:27 UTC, rishabhpoddar requested changes
Overall it seems good. However, I think the number of functions is rather too many? Let's discuss on a call

2021-11-17 06:27 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessDevice.java
> +    public PasswordlessDevice(String loginAttemptId, String email, String phoneNumber, int failedAttempts) {
I don't like that we are using `loginAttemptId` in the input and assigning it to `deviceIdHash`. Perhaps we should raname the input to `deviceIdHash`?

2021-11-17 06:27 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessDevice.java
> +    public final int failedAttempts;
Rename this to `failedCodeInputAttemptCount`

2021-11-17 06:27 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/UserInfo.java
> +    public UserInfo(String id, String email, String phoneNumber, long timeJoined) {
Mark `email` and `phoneNumber` as `@Nullable`. In the constructor, check that if both are `null`, then throw an Exception - like `throw new Exception("Both email and phoneNumber cannot be null")`?

2021-11-17 06:27 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/UserInfo.java
> +public class UserInfo extends AuthRecipeUserInfo {
Since we are adding a new user type, it will also require changes to `io.supertokens.test.AuthRecipeTest`

2021-11-17 06:27 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/sqlStorage/PasswordlessSQLStorage.java
> +            throws StorageQueryException, DuplicateEmailException, UnknownUserIdException;
I think this can be one function like `updateUser_Transaction(TransactionConnection con, @Nonnull String userId, @Nullable String email, @Nullable String phoneNumber) throws StorageQueryException, DuplicatePhoneNumberException, UnknownUserIdException, DuplicateEmailException;`

2021-11-17 10:04 UTC, rishabhpoddar requested changes

2021-11-17 10:04 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/sqlStorage/PasswordlessSQLStorage.java
> +            @Nonnull String phoneNumber) throws StorageQueryException, DuplicateDeviceIdHashException;
Can combine this into one.

2021-11-17 13:02 UTC, porcellus commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessDevice.java
> +    public final int failedAttempts;
Should we rename it in the DB as well? I assumed `failedCodeInputAttemptCount` would only be renamed on the API.

2021-11-17 13:15 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessDevice.java
> +    public final int failedAttempts;
Sure. We can change the column name in the db to `failed_code_input_attempt_count`

2021-11-17 13:24 UTC, rishabhpoddar requested changes
Are you sure that you want to remove `getDevice`, `getCodesOfDevice` and `getCodeByLinkCodeHash` from the interface? I ask cause without those, we will have to use the trasaction versions of these functions which means that those will have a `FOR UPDATE` in them.

2021-11-17 13:24 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/exception/EmptyContactInfoException.java
> +public class EmptyContactInfoException extends EmailPasswordException {
Not sure why this is `EmailPasswordException`. Maybe we don't even need this class. Instead, you can use a RuntimeException like `IllegalArgumentException`.

2021-11-17 13:24 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/UserInfo.java
> +            throw new EmptyContactInfoException();
Consider throwing a RuntimeException here like `IllegalArgumentException`. That way, you won't need to add any new exception to the function signature. Also, this is fine since the only time this exception would get thrown is if there is a bug in our code

2021-11-17 13:30 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessDevice.java
> +    public final int failedAttempts;
As discussed, we can continue to use `failed_attempts` everywhere internally - and change it to `failedCodeInputAttemptCount` in the API layer.

2021-11-17 15:34 UTC, rishabhpoddar approved these changes

2021-11-18 17:46 UTC, rishabhpoddar approved these changes

2021-11-18 18:10 UTC, rishabhpoddar requested changes

2021-11-18 18:10 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessStorage.java
> +            DuplicateCodeIdException, DuplicateLinkCodeHashException;
Instead of giving so many arguments, perhaps it would be good to change this to `createDeviceWithCode(PasswordlessDevice device, PasswordlessCode code)`

2021-11-18 18:10 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessStorage.java
> +            throws StorageQueryException, UnknownDeviceIdHash, DuplicateCodeIdException, DuplicateLinkCodeHashException;
Perhaps we should change it to `createCode(PasswordlessCode code)`?

2021-11-18 18:10 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessStorage.java
> +            DuplicateUserIdException;
Perhaps change this to `createUser(UserInfo user)`?

2021-11-18 23:00 UTC, porcellus commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessStorage.java
> +            DuplicateCodeIdException, DuplicateLinkCodeHashException;
Device and Code have an overlap (deviceIdHash) and Device has an unused field (failedAttempts) so I only extracted the Code arguments and left email and phoneNumber. I'm not sure if I like that the deviceIdHash is defined through the code, but it looks cleaner.

2021-11-20 06:15 UTC, rishabhpoddar approved these changes

2021-11-24 04:54 UTC, rishabhpoddar requested changes

2021-11-24 04:54 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessCode.java
> +            return false;
I think it's more convention to check `if (obj instanceof PasswordlessCode)`

2021-11-24 04:54 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessCode.java
> +        if (this == obj)
I really prefer if you add brackets around all these `if`s.

2021-11-24 16:58 UTC, rishabhpoddar approved these changes

2021-12-20 10:29 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/passwordless/PasswordlessStorage.java
> +    void createDeviceWithCode(@Nullable String email, @Nullable String phoneNumber, @Nonnull String linkCodeHash,
Change to `linkCodeSalt`

2021-12-20 11:56 UTC, rishabhpoddar approved these changes

2022-01-14 05:25 UTC, merged