feat: Adds functions for dashboard APIs
supertokens/supertokens-plugin-interface pull request #52
Opened 2023-02-01 08:19 UTC by jscyo

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-02-08 06:01 UTC, nkshah2 requested changes

2023-02-08 06:01 UTC, nkshah2 commented on src/main/java/io/supertokens/pluginInterface/RECIPE_ID.java
> +    USER_ROLES("userroles"), USER_ID_MAPPING("useridmapping"), DASHBOARD("dashboard");
Maybe enum and class names and recipe name should be user management dashboard

2023-02-14 08:00 UTC, rishabhpoddar requested changes

2023-02-14 08:00 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/dashboard/sqlStorage/DashboardSQLStorage.java
> +    void updateDashboardUsersPasswordWithUserId_Transaction(TransactionConnection con, String userId, String newPassword) throws StorageQueryException;
these should also throw UserIdNotFoundException

2023-02-21 09:38 UTC, rishabhpoddar approved these changes

2023-02-21 09:41 UTC, merged