feat: Define TOTP recipe plugin interface
supertokens/supertokens-plugin-interface pull request #53
Opened 2023-02-06 10:34 UTC by KShivendu

## Summary of change

Define TOTP recipe plugin interface

## Related issues
- Link to issue1 here
- Link to issue1 here

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [x] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2023-02-08 10:48 UTC, rishabhpoddar requested changes

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +    void createDevice(String userId, String deviceName, String secret, int skew, int period)
```suggestion
    void createDevice(TotpDevice device)
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPDevice.java
> +    public final Boolean verified;
```suggestion
    public final boolean verified;
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPDevice.java
> +package io.supertokens.pluginInterface.totp;
Add totp to RECIPE_ID.java

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/exception/DeviceAlreadyExistsException.java
> +    private static final long serialVersionUID = 6848053563771647272L; // How's this decided ?
remove all this

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +            throws StorageQueryException, NotEnabledException;
```suggestion
    TOTPDevice[] getDevices(String userId)
            throws StorageQueryException, NotEnabledException;
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/exception/NotEnabledException.java
> +public class NotEnabledException extends EmailPasswordException {
```suggestion
public class TotpNotEnabledException extends EmailPasswordException {
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +    String[] getDeviceNames(String userId) throws StorageQueryException;
```suggestion
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +    void verifyDevice(String userId, String deviceName)
```suggestion
    void markDeviceAsVerified(String userId, String deviceName)
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +            throws StorageQueryException, InvalidCodeException, NotEnabledException, UnknownDeviceException;
```suggestion
            throws StorageQueryException, NotEnabledException, UnknownDeviceException;
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +            throws StorageQueryException, InvalidCodeException, NotEnabledException, LimitReachedException;
```suggestion
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +    void deleteDevice(String userId, String deviceName) throws StorageQueryException, NotEnabledException;
```suggestion
    void deleteDevice(String userId, String deviceName) throws StorageQueryException, NotEnabledException, UnknownDeviceException;
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +
Need functions for:
- inserting into totp_used_codes
- getting info from totp_used_codes based on userId
- remove expired codes from totp_used_codes

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/exception/LimitReachedException.java
> +
remove this exception

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/exception/InvalidCodeException.java
> +import io.supertokens.pluginInterface.emailpassword.exceptions.EmailPasswordException;
remove this

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPUsedCode.java
> +    public final Boolean isValidCode;
```suggestion
    public final boolean isValidCode;
```

2023-02-08 10:48 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPUsedCode.java
> +    public final Boolean isValidCode;
```suggestion
    public final boolean isValidCode;
```

2023-02-09 06:15 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPDevice.java
> +package io.supertokens.pluginInterface.totp;
done.

2023-02-09 06:15 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPDevice.java
> +    public final Boolean verified;
done.

2023-02-09 06:16 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +            throws StorageQueryException, InvalidCodeException, NotEnabledException, LimitReachedException;
done

2023-02-09 06:16 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +    void createDevice(String userId, String deviceName, String secret, int skew, int period)
done

2023-02-09 06:16 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +    void verifyDevice(String userId, String deviceName)
done

2023-02-09 06:17 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +            throws StorageQueryException, InvalidCodeException, NotEnabledException, UnknownDeviceException;
done

2023-02-09 06:17 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +    void deleteDevice(String userId, String deviceName) throws StorageQueryException, NotEnabledException;
done

2023-02-09 06:17 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +            throws StorageQueryException, NotEnabledException;
done

2023-02-09 06:20 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPUsedCode.java
> +    public final Boolean isValidCode;
done

2023-02-09 06:20 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +    String[] getDeviceNames(String userId) throws StorageQueryException;
done

2023-02-09 06:20 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPUsedCode.java
> +    public final Boolean isValidCode;
done

2023-02-09 06:21 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/exception/NotEnabledException.java
> +public class NotEnabledException extends EmailPasswordException {
done.

2023-02-09 06:21 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/exception/LimitReachedException.java
> +
done

2023-02-09 06:22 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/exception/InvalidCodeException.java
> +import io.supertokens.pluginInterface.emailpassword.exceptions.EmailPasswordException;
done.

2023-02-09 06:46 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +
done

2023-02-09 07:18 UTC, rishabhpoddar requested changes

2023-02-09 07:18 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +                        throws StorageQueryException, TotpNotEnabledException;
```suggestion
        TOTPDevice[] getDevices(String userId)
                        throws StorageQueryException;
```

2023-02-09 07:18 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +                        throws StorageQueryException;
```suggestion
        void insertUsedCode(TOTPUsedCode code)
                        throws StorageQueryException, TotpNotEnabledException;

        // Get totp used code based on userId:
        TOTPUsedCode[] getUsedCodes(String userId)
                        throws StorageQueryException, TotpNotEnabledException;
```

2023-02-09 07:18 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +        void insertUsedCode(TOTPUsedCode code)
```suggestion
        boolean insertUsedCode(TOTPUsedCode code)
```

2023-02-09 07:21 UTC, rishabhpoddar approved these changes

2023-02-09 07:22 UTC, rishabhpoddar approved these changes

2023-02-09 09:16 UTC, rishabhpoddar approved these changes

2023-02-09 14:25 UTC, rishabhpoddar requested changes

2023-02-09 14:25 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/exception/TotpNotEnabledException.java
> +public class TotpNotEnabledException extends EmailPasswordException {
These should not extend EmailPasswordException. Instead, they should all just extend Exception.

2023-02-09 14:25 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/exception/TotpNotEnabledException.java
> +public class TotpNotEnabledException extends EmailPasswordException {
This bug is also in other exceptions of this interface.. i know. But at least fix these totp exception types

2023-02-11 06:08 UTC, rishabhpoddar requested changes

2023-02-11 06:08 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +                        throws StorageQueryException, TotpNotEnabledException, UnknownDeviceException;
i don't see the usefulness of throwing `TotpNotEnabledException` from these functions ( markDeviceAsVerified, deleteDevice, updateDeviceName)- cause the primary key in the tables is (user_id, device_name). So failure to update those rows will always just result in `UnknownDeviceException` exception.

2023-02-13 13:22 UTC, rishabhpoddar approved these changes

2023-02-21 08:05 UTC, rishabhpoddar approved these changes

2023-02-21 18:09 UTC, rishabhpoddar approved these changes

2023-02-23 12:08 UTC, rishabhpoddar requested changes

2023-02-23 12:08 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
>  public interface TOTPStorage extends AuthRecipeStorage {
```suggestion
public interface TOTPStorage extends NonAuthRecipeStorage {
```

2023-02-23 12:08 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +        void deleteAllDataForUser(String userId)
```suggestion
        void deleteAllTOTPRelatedDataForUser(String userId)
```

2023-02-28 13:27 UTC, rishabhpoddar requested changes

2023-02-28 13:27 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
>                          throws StorageQueryException;
this should not be required anymore

2023-02-28 13:44 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
>                          throws StorageQueryException;
Done.

2023-02-28 13:45 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/totp/TOTPStorage.java
> +        void deleteAllDataForUser(String userId)
Removed now.

2023-02-28 15:48 UTC, rishabhpoddar approved these changes

2023-02-28 16:01 UTC, rishabhpoddar approved these changes

2023-03-03 08:20 UTC, rishabhpoddar approved these changes

2023-03-10 07:10 UTC, rishabhpoddar requested changes

2023-03-10 07:10 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/totp/sqlStorage/TOTPSQLStorage.java
> +            throws StorageQueryException;
remove this and add getDevices_Transaction(TransactionConnection con, String userId)

2023-03-11 05:49 UTC, rishabhpoddar approved these changes

2023-03-27 13:50 UTC, merged