fix: new exceptions
supertokens/supertokens-plugin-interface pull request #56
Opened 2023-02-27 10:09 UTC by sattvikc

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-02-27 10:46 UTC, rishabhpoddar requested changes

2023-02-27 10:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/MultitenancyStorage.java
> +            DuplicateThirdPartyIdException, DuplicateClientTypeException, StorageQueryException;
```suggestion
    void overwriteTenantConfig(TenantConfig config) throws TenantOrAppNotFoundException, StorageQueryException;
```

2023-02-27 10:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java
> +            }
if the user sets it to null in the API, it should get returned as null from the API call

2023-02-27 11:05 UTC, rishabhpoddar requested changes

2023-02-27 11:05 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java
> +            }
no need to do this

2023-02-28 07:52 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java
> +            }
removed. Added check in the postgres plugin.

2023-02-28 08:46 UTC, rishabhpoddar requested changes

2023-02-28 08:46 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/multitenancy/ThirdPartyConfig.java
> -        @Nullable
@Nonnull

2023-02-28 08:48 UTC, rishabhpoddar approved these changes

2023-02-28 08:48 UTC, merged