fix: getByUserById to take tenantIdentifier instead of appIdentifier
supertokens/supertokens-plugin-interface pull request #58
Opened 2023-03-13 06:49 UTC by sattvikc

## Summary of change

Using tenantIdentifier for getting user by id, to avoid cross-tenant requests.

## Related issues
- Link to issue1 here
- Link to issue1 here

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-03-13 08:50 UTC, rishabhpoddar requested changes

2023-03-13 08:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/emailpassword/EmailPasswordStorage.java
> +    UserInfo getUserInfoUsingId(TenantIdentifier tenantIdentifier, String id) throws StorageQueryException;
this should be appIdentifier only - cause user ID is unique per app, not per tenant

2023-03-13 08:50 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/emailpassword/sqlStorage/EmailPasswordSQLStorage.java
> +    UserInfo getUserInfoUsingId_Transaction(TenantIdentifier tenantIdentifier, TransactionConnection con, String userId)
this should be appIdentifier only - cause user ID is unique per app, not per tenant

2023-03-22 08:08 UTC, sattvikc commented
This PR is no more valid.

2023-03-22 08:08 UTC, closed without merging