fix: Multitenant session
supertokens/supertokens-plugin-interface pull request #76
Opened 2023-04-03 11:52 UTC by sattvikc

## Summary of change
(A few sentences about this PR)

## Related issues
- Link to issue1 here
- Link to issue1 here

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-04-04 11:51 UTC, rishabhpoddar requested changes

2023-04-04 11:51 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/session/sqlStorage/SessionSQLStorage.java
> +            throws StorageQueryException, TenantOrAppNotFoundException;
setRefreshTokenSigningKey_Transaction -> should also throw TenantOrAppNotFoundException

2023-04-05 07:59 UTC, sattvikc commented on src/main/java/io/supertokens/pluginInterface/session/sqlStorage/SessionSQLStorage.java
> +            throws StorageQueryException, TenantOrAppNotFoundException;
Done

2023-04-05 11:06 UTC, rishabhpoddar approved these changes

2023-04-05 11:06 UTC, merged