feat: Introduce MFA recipe
supertokens/supertokens-plugin-interface pull request #87
Opened 2023-04-27 06:25 UTC by KShivendu

## Summary of change

Introduce MFA recipe

## Related issues
- https://github.com/supertokens/supertokens-core/issues/648

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [x] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

2023-04-28 08:34 UTC, rishabhpoddar approved these changes

2023-05-04 11:29 UTC, KShivendu commented
Please check the latest change before merging. https://github.com/supertokens/supertokens-plugin-interface/pull/87/commits/77a78b0bc6cb227afb5bd315f73bfb51a38c22f7

2023-05-08 06:32 UTC, rishabhpoddar requested changes

2023-05-08 06:32 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaStorage.java
> +    boolean deleteUser(AppIdentifier tenantIdentifier, String userId) throws StorageQueryException;
you will also need a function to delete mfa user's for a specific tenant

2023-05-08 06:32 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaStorage.java
> +    boolean deleteUser(AppIdentifier tenantIdentifier, String userId) throws StorageQueryException;
```suggestion
    boolean deleteUser(AppIdentifier appIdentifier, String userId) throws StorageQueryException;
```

2023-05-10 10:56 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaStorage.java
> +    boolean deleteUser(AppIdentifier tenantIdentifier, String userId) throws StorageQueryException;
fixed.

2023-05-10 13:13 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaStorage.java
> +    boolean deleteUser(AppIdentifier tenantIdentifier, String userId) throws StorageQueryException;
Added

2023-05-10 14:59 UTC, rishabhpoddar requested changes

2023-05-10 14:59 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaStorage.java
> +    boolean deleteUserFromTenant(TenantIdentifier tenantIdentifier, String userId) throws StorageQueryException;
```suggestion
    boolean deleteMFAUser(AppIdentifier appIdentifier, String userId) throws StorageQueryException;

    // Delete a user from a tenant (with all the relevant factors)
    boolean deleteMFAUser(TenantIdentifier tenantIdentifier, String userId) throws StorageQueryException;
```

2023-05-15 13:07 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/mfa/MfaStorage.java
> +    boolean deleteUserFromTenant(TenantIdentifier tenantIdentifier, String userId) throws StorageQueryException;
Done

2023-05-22 10:50 UTC, rishabhpoddar approved these changes

2023-05-26 11:32 UTC, rishabhpoddar approved these changes

2023-06-23 13:55 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/ActiveUsersStorage.java
> +    /* Count the number of users who have enabled MFA */
What's the use of `jar/plugin-interface-2.23.0.jar`?  If none, remove it.

2023-06-23 13:58 UTC, KShivendu commented on src/main/java/io/supertokens/pluginInterface/ActiveUsersStorage.java
> +    /* Count the number of users who have enabled MFA */
Compare the current PR with https://github.com/supertokens/supertokens-plugin-interface/pull/87/files/a67d94df05fb816a4695a1e5309daded3c26d570..6e5f1ec5d2281af9e596f48e875f34540716044b once

2024-03-13 15:09 UTC, merged