Added missing exception on Oauth2 methods
supertokens/supertokens-plugin-interface pull request #99
Opened 2023-05-26 16:04 UTC by AdithyaSSup

## Summary of change
Added missing exception on `oauth2CreateClient` method and changes method signature.
## Related issues
- https://github.com/supertokens/supertokens-core/issues/582

## Checklist for important updates
- [ ] Changelog has been updated
- [ ] Changes to the version if needed
   - In `build.gradle`
- [ ] Had installed and ran the pre-commit hook
- [ ] Issue this PR against the latest non released version branch.
   - To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
   - If no such branch exists, then create one from the latest released branch.

## Remaining TODOs for this PR
- [ ] Item1
- [ ] Item2

2023-05-26 16:11 UTC, rishabhpoddar requested changes

2023-05-26 16:11 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Client.java
> +        return list1.equals(list2);
does the order of the items in the list matter here when using the `.equals` function?

2023-05-29 03:19 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Client.java
> +        return list1.equals(list2);
Yes order matters.. which is required in our case. `equals()` method makes a equality check both on elements as well as on order.

2023-05-29 05:58 UTC, rishabhpoddar requested changes

2023-05-29 05:58 UTC, rishabhpoddar commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Client.java
> +        return list1.equals(list2);
Change this to check where order deosn't matter

2023-05-29 06:50 UTC, AdithyaSSup commented on src/main/java/io/supertokens/pluginInterface/oauth2/OAuth2Client.java
> +        return list1.equals(list2);
Changes made.

2023-05-29 07:42 UTC, rishabhpoddar approved these changes

2023-05-29 07:42 UTC, merged